{
  dotfilesSymlink,
  pkgs,
}: let
  treesitter-parsers = pkgs.symlinkJoin {
    name = "treesitter-parsers";
    paths = pkgs.vimPlugins.nvim-treesitter.withAllGrammars.dependencies;
  };
in {
  fish.source = dotfilesSymlink "fish";
  wezterm.source = dotfilesSymlink "wezterm";
  vesktop.source = dotfilesSymlink "vesktop";
  "btop/themes".source = dotfilesSymlink "btop/themes";
  "cumulus".source = dotfilesSymlink "cumulus";

  "nvim/lua".source = dotfilesSymlink "nvim/lua";
  "nvim/lazy-lock.json".source = dotfilesSymlink "nvim/lazy-lock.json";
  "nvim/init.lua".text = ''
    -- Warning! Autogenerated file by Home Manager
    -- Do NOT edit it directly, all changes may be removed

    -- Add Treesitter Path for parsers
    vim.opt.rtp:prepend("${treesitter-parsers}")

    -- Invoke the real config
    require("core")
  '';
}
