-- Warning! Autogenerated file by cumulus
-- Do NOT edit it directly, all changes may be removed

return {
  "folke/tokyonight.nvim",
  lazy = false,
  priority = 1000,
  opts = {
    style = "night",

    on_colors = function(colors)
      colors.bg = "#16161E"
    end
}

}