# Warning! Autogenerated file by cumulus
# Do NOT edit it directly, all changes may be removed

''
@-moz-document url(about:home), url(about:newtab) {
  body {
    background-color: #16161E !important;
  }

  .search-inner-wrapper {
    --newtab-background-color-secondary: #565f89 !important;
  }
}
''