# Warning! Autogenerated file by cumulus
# Do NOT edit it directly, all changes may be removed

''
#navigator-toolbox {
  background-color: #16161E !important;
}

:root {
  --toolbar-bgcolor: #16161E !important;
  --tab-selected-bgcolor: #565f89 !important;
}

#TabsToolbar {
  --lwt-tab-line-color: #00000000 !important;
}

#nav-bar {
  border-top: none !important;
}

#navigator-toolbox {
  border-bottom: none !important;
}

.titlebar-buttonbox-container {
  display: none !important;
}

#tabbrowser-tabs {
  border-inline-start: none !important;
}

.titlebar-spacer {
  width: 0 !important;
}
''